#if you use custom configurations in your pjsip.confg file, then you have to add this in extension.confg in /etc/asterisk/extensions.confg.

[local]

exten => 100,1,NoOp(Call to 100)
 same => n,Answer()
 same => n,Dial(PJSIP/101,10)
 same => n,Hangup()


exten => 101,1,NoOp(Call to 101)
 same => n,Answer()
 same => n,Dial(PJSIP/100,10)
 same => n,Hangup()
